name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Curl Deploy Hook
        run: curl -X GET ${{ secrets.RENDER_DEPLOY_HOOK }}
